analytics: {}
color:
  brandColors:
    - '#7F9CBE'
    - '#F7F1E3'
    - '#857661'
    - '#141412'
    - '#4B4D42'
  brandStrength: 0.006756
  lightness: 0.5
  rhythmicContrast: 0.5
  saturation: 0.5
cta: {}
layout_spectrum: 0.193693
name: 'Ola&Krzysiek'
opengraph: {}
purpose: []
typography_spectrum: 0.65392
