typography_spectrum: 0.19520770711824298
color:
  brandColors:
    - '#E6E2AF'
    - '#A7A37E'
    - '#EFECCA'
    - '#046380'
    - '#002F2F'
  brandStrength: 0.8883684298489243
  lightness: 0.4503232575953007
  saturation: 0.46681961067952216
  rhythmicContrast: 0.7466618386097252
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.20402
analytics:
  google: null
  facebook: null
  twitter: null
name: Ola&Krzysiek
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Barcelona
    id: bf1a2243-1b97-423d-be49-cf2a6e491c4e
    type: content
favicon: null
title: Ola&Krzysiek
purpose: []
