typography_spectrum: 0.19520770711824298
color:
  brandColors:
    - '#E6E2AF'
    - '#A7A37E'
    - '#EFECCA'
    - '#046380'
    - '#002F2F'
  brandStrength: 0.8883684298489243
  lightness: 0.4503232575953007
  saturation: 0.46681961067952216
  rhythmicContrast: 0.7466618386097252
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.20402
analytics:
  google: null
  facebook: null
  twitter: null
name: Ola&Krzysiek
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Barcelona
    id: bf1a2243-1b97-423d-be49-cf2a6e491c4e
    type: content
  - name: A Coruña
    id: b57ea0ae-a4ba-4ed2-9992-701d1e606b4c
    type: content
  - name: Dzień 13 Santiago de Compostela
    id: f5dbc021-6188-4b80-b41d-9c2bb7263678
    type: content
  - name: Dzień 12 Santa Irene - Monte do Gozo.
    id: ec6db1bf-28f8-47e4-a9f5-45392a849b7c
    type: content
  - name: Dzień 11 Boente - Arzua - Santa Irene
    id: ef57ea59-42cd-4ee1-acac-5ebbad3ad360
    type: content
  - name: Dzień 10 As Seixas -Melide (gdzie wchodzimy na Camino Francés) - Boente
    id: 38e3ed0f-0434-410c-a7a3-d0154e5d8735
    type: content
favicon: null
title: Ola&Krzysiek
purpose: []
