name: Ola&Krzysiek
favicon: null
layout_spectrum: 0
typography_spectrum: 0.20406
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7F9CBE'
    - '#F7F1E3'
    - '#857661'
    - '#141412'
    - '#4B4D42'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
