name: 'Ola&Krzysiek'
favicon: null
layout_spectrum: 0.27643
typography_spectrum: 0.65392
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9fafe'
    - '#d6dae3'
    - '#2c2827'
    - '#706f6b'
    - '#a8a7a3'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
